import assert from 'node:assert/strict';
import { spawn, spawnSync, type ChildProcess } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { after, before, describe, it } from 'node:test';
import { writeRunRecord, type RunRecord } from '../src/core/registry.ts';
import { startWebServer, type WebServerHandle } from '../src/web/server.ts';
import type { RunSource } from '../src/web/run-source.ts';

// ---------------------------------------------------------------------------
// External-run PTY refusal + GET /health (spec 0.8.0 §7).
//
// /health needs no PTY, so those cases drive the real startWebServer
// in-process (node:http, fine under tsx). The PTY-refusal cases need real
// bun-pty sessions ("bun-pty PTYs only construct under Bun" — see
// tests/web-pty.test.ts), so they run the server inside a bun subprocess
// runner generated below: the runner constructs a PtyManager itself, spawns
// sessions with the runIds under test DIRECTLY (not via HTTP), and passes
// the manager as opts.ptyManager, exactly like tests/helpers/web-server-runner.ts.
// ---------------------------------------------------------------------------

const T0 = 1_700_000_000_000;
const SERVER_MOD = fileURLToPath(new URL('../src/web/server.ts', import.meta.url));
const PTY_MANAGER_MOD = fileURLToPath(new URL('../src/web/pty-manager.ts', import.meta.url));
const isBun = spawnSync('bun', ['--version'], { encoding: 'utf8' }).status === 0;

function extRec(): RunRecord {
  // Minimal external record: no local pid/cwd/transcript (0.9.0 contract).
  return { runId: 'run-ext-1', agent: 'claude', startedAt: T0, source: 'external', producer: 'test-bridge' };
}

function locRec(): RunRecord {
  return {
    runId: 'run-loc-1',
    agent: 'claude',
    pid: 4242,
    cwd: '/tmp/proj',
    promptPreview: 'local run',
    startedAt: T0,
    updatedAt: T0,
    status: 'running',
  };
}

const fakeSource: RunSource = {
  start: async () => {},
  snapshot: () => [],
  stop: async () => {},
  health: () => ({ healthy: false, detail: 'down' }),
};

// ------------------------------------------------------- /health (in-process)

describe('GET /health (in-process startWebServer)', () => {
  const servers: WebServerHandle[] = [];
  const dirs: string[] = [];

  async function boot(opts: { token?: string; runSource?: RunSource; sourceUrl?: string }): Promise<string> {
    const stateDir = mkdtempSync(join(tmpdir(), 'harness-pty-health-'));
    dirs.push(stateDir);
    const handle = await startWebServer({
      port: 0,
      host: '127.0.0.1',
      stateDir,
      ...(opts.token === undefined ? {} : { token: opts.token }),
      ...(opts.runSource === undefined ? {} : { runSource: opts.runSource }),
      ...(opts.sourceUrl === undefined ? {} : { sourceUrl: opts.sourceUrl }),
    });
    servers.push(handle);
    return `http://127.0.0.1:${handle.port}`;
  }

  after(async () => {
    for (const s of servers.splice(0)) await s.close();
    for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true });
  });

  it('no source configured → 200 {ok:true, source:null, sourceHealthy:null}', async () => {
    const base = await boot({});
    const res = await fetch(`${base}/health`);
    assert.equal(res.status, 200);
    assert.deepEqual(await res.json(), { ok: true, source: null, sourceHealthy: null });
  });

  it('fake source + sourceUrl → 200 {ok:true, source:"http://x/y", sourceHealthy:false}', async () => {
    const base = await boot({ runSource: fakeSource, sourceUrl: 'http://x/y' });
    const res = await fetch(`${base}/health`);
    assert.equal(res.status, 200);
    assert.deepEqual(await res.json(), { ok: true, source: 'http://x/y', sourceHealthy: false });
  });

  it('token-configured server: no-token /health gets the same status as no-token /api/runs', async () => {
    const base = await boot({ token: 'sekret' });
    const health = await fetch(`${base}/health`);
    const runs = await fetch(`${base}/api/runs`);
    assert.equal(health.status, runs.status, '/health must share the /api/runs auth policy');
  });
});

// ------------------------------------- PTY refusal (bun subprocess + real PTYs)

const RUNNER_SRC = `// Generated by tests/web-pty-health.test.ts — do not edit.
const [stateDir = '', token = '', cfgRaw = '{}'] = process.argv.slice(2);
const cfg = JSON.parse(cfgRaw) as { spawnRunIds?: string[] };
const { PtyManager } = await import('${PTY_MANAGER_MOD}');
const { startWebServer } = await import('${SERVER_MOD}');
const ptyManager = new PtyManager();
const spawned: { id: string; runId: string }[] = [];
for (const runId of cfg.spawnRunIds ?? []) {
  const info = await ptyManager.spawn({ command: 'sleep', args: ['60'], runId });
  spawned.push({ id: info.id, runId });
}
const handle = await startWebServer({
  port: 0,
  host: '127.0.0.1',
  token: token === '' ? undefined : token,
  stateDir,
  ptyManager,
});
process.stdout.write(\`READY \${handle.port} \${JSON.stringify(spawned)}\n\`);
const shutdown = (): void => {
  void handle.close().then(
    () => { ptyManager.dispose(); process.exit(0); },
    () => { ptyManager.dispose(); process.exit(1); },
  );
};
process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
`;

interface SpawnedSession {
  id: string;
  runId: string;
}

describe('external-run PTY refusal (bun subprocess)', { skip: isBun ? false : 'bun not on PATH' }, () => {
  const dirs: string[] = [];
  const children: ChildProcess[] = [];
  let base = '';
  let extSession = '';
  let locSession = '';

  async function killChild(c: ChildProcess): Promise<void> {
    if (c.exitCode !== null || c.signalCode) return;
    await new Promise<void>((resolve) => {
      const escalated = setTimeout(() => {
        try {
          c.kill('SIGKILL');
        } catch {
          /* gone */
        }
      }, 3_000);
      c.once('exit', () => {
        clearTimeout(escalated);
        resolve();
      });
      c.kill('SIGTERM');
    });
  }

  async function post(pathname: string, body: string): Promise<Response> {
    return fetch(`http://127.0.0.1:${basePort}${pathname}`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', authorization: 'Bearer sekret' },
      body,
    });
  }

  let basePort = 0;

  before(async () => {
    const stateDir = mkdtempSync(join(tmpdir(), 'harness-pty-health-bun-'));
    dirs.push(stateDir);
    writeRunRecord(stateDir, extRec());
    writeRunRecord(stateDir, locRec());
    const runnerDir = mkdtempSync(join(tmpdir(), 'harness-pty-health-runner-'));
    dirs.push(runnerDir);
    const runnerPath = join(runnerDir, 'runner.ts');
    writeFileSync(runnerPath, RUNNER_SRC);

    const child = spawn('bun', [runnerPath, stateDir, 'sekret', JSON.stringify({ spawnRunIds: ['run-ext-1', 'run-loc-1'] })], {
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    children.push(child);
    let out = '';
    let err = '';
    child.stdout!.setEncoding('utf8');
    child.stderr!.setEncoding('utf8');
    child.stderr!.on('data', (c: string) => {
      err += c;
    });
    const ready = await new Promise<{ port: number; spawned: SpawnedSession[] }>((resolve, reject) => {
      const deadline = setTimeout(
        () => reject(new Error(`runner never became ready; stderr: ${err.slice(-400)}`)),
        20_000,
      );
      child.stdout!.on('data', (c: string) => {
        out += c;
        const m = /^READY (\d+) (.+)$/m.exec(out);
        if (m) {
          clearTimeout(deadline);
          resolve({ port: Number(m[1]), spawned: JSON.parse(m[2]!) as SpawnedSession[] });
        }
      });
      child.once('exit', (code, sig) => {
        clearTimeout(deadline);
        reject(new Error(`runner exited early (${code}/${sig}); stderr: ${err.slice(-400)}`));
      });
    });
    basePort = ready.port;
    base = `http://127.0.0.1:${ready.port}`;
    const ext = ready.spawned.find((s) => s.runId === 'run-ext-1');
    const loc = ready.spawned.find((s) => s.runId === 'run-loc-1');
    assert.ok(ext, 'runner did not spawn the external-runId session');
    assert.ok(loc, 'runner did not spawn the local-runId session');
    extSession = ext!.id;
    locSession = loc!.id;
  });

  after(async () => {
    for (const c of children.splice(0)) await killChild(c);
    for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true });
  });

  it('POST /api/pty with an external runId → 409 with the external-run message', async () => {
    const res = await post('/api/pty', JSON.stringify({ command: 'sleep', args: ['1'], runId: 'run-ext-1' }));
    assert.equal(res.status, 409);
    const body = (await res.json()) as { error: string };
    assert.equal(body.error, 'run run-ext-1 is external — no local PTY exists');
  });

  it('POST /api/pty with a local runId → 201, then kill → 200', async () => {
    const res = await post('/api/pty', JSON.stringify({ command: 'sleep', args: ['1'], runId: 'run-loc-1' }));
    assert.equal(res.status, 201);
    const info = (await res.json()) as { id: string };
    const kill = await post(`/api/pty/${info.id}/kill`, '');
    assert.equal(kill.status, 200);
  });

  it('POST /api/pty with an unknown runId → 201, then kill → 200', async () => {
    const res = await post('/api/pty', JSON.stringify({ command: 'sleep', args: ['1'], runId: 'run-no-such-9' }));
    assert.equal(res.status, 201);
    const info = (await res.json()) as { id: string };
    const kill = await post(`/api/pty/${info.id}/kill`, '');
    assert.equal(kill.status, 200);
  });

  it('GET (non-upgrade probe) /ws/pty/<external-runId session> → 409 external-run message', async () => {
    const res = await fetch(`${base}/ws/pty/${extSession}?token=sekret`);
    assert.equal(res.status, 409);
    const body = (await res.json()) as { error: string };
    assert.equal(body.error, 'run run-ext-1 is external — no local PTY exists');
  });

  it('GET /ws/pty/<local-runId session> probe → its normal status, NOT 409', async () => {
    const res = await fetch(`${base}/ws/pty/${locSession}?token=sekret`);
    assert.notEqual(res.status, 409, 'local-runId session probe must not be refused as external');
  });
});
